# <font color="steelblue">240. Ejercicios inferencia estadística sobre proporciones</font>

**Material desarrollado por los [equipos de trabajo de IA4LEGOS](https://ia4legos.umh.es/)**


**Fecha última edición**: 10/05/2025

**Licencia**: <small><a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br /></small>

No olvides hacer una copia si deseas utilizarlo. Al usar estos contenidos, aceptas nuestros términos de uso y nuestra política de privacidad.

## <font color='steelblue'>Introducción</font>

**Descripción:** Colección de ejercicios sobre variables aleatorias continuas.

In [ ]:
# Cargamos módulos de análisis numérico
import numpy as np          # importamos numpy como np
import pandas as pd         # importamos pandas como pd
import math                 # importamos módulo para cáculos matemáticos

# Cargamos módulos de análisis gráficos
from plotnine import *      # importamos módulo para gráficos con ggplot
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
%config InlineBackend.figure_format = 'retina'

from scipy import stats

Cargamos el repositorio con los bancos de datos

In [ ]:
# Clonamos el repositorio github con todos los ficheros
!git clone 'https://github.com/jmsocuellamos/RepoStatsDatabase.git'
# Cambímaos al directorio donde se encuentran los datos
%cd /content/RepoStatsDatabase

Cloning into 'RepoStatsDatabase'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 29 (delta 6), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (29/29), 160.90 KiB | 3.04 MiB/s, done.
Resolving deltas: 100% (6/6), done.
/content/RepoStatsDatabase

### **EJ001.**

Una cadena de supermercados vende pan recién horneado. Los cálculos realizados conforme a la teoría de inventarios indican que para balancear los costos del pan no vendido (por estar duro) y la satisfacción de los clientes, la cadena debería agotar sus existencias de pan el 20% de los días. Se elige una muestra aleatoria de 50 tiendas y se comprobó que 14 de ellas quedaron desabastecidas. Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 1% y establece a que conclusión puedes llegar con la información recogida?
* ¿Cómo interpretamos el intervalo de confianza que hemos obtenido?

Puedes cargar los datos para resolver este ejercicio con:

In [ ]:
ifprop001 = pd.read_excel("Infer_prop.xlsx", sheet_name="IFprop001")
ifprop001.head()

   Tienda Desabastecida
0       1            Si
1       2            Si
2       3            Si
3       4            Si
4       5            Si

### **EJ002.**

La opinión prevaleciente entre los analistas de la bolsa de valores es que sólo el 35% de las ofertas públicas de compra resultan en una adquisición real. Un grupo de analistas cree que incluso este porcentaje es mucho más elevado. Para poner a prueba sus creencias, el grupo planea rastrear 20 ofertas públicas de compra para ver cuántas de ellas derivan en una adquisición. De las 20 ofertas tan sólo dos de las ofertas resultaron en una adquisición. Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?
* ¿Cómo interpretamos el intervalo de confianza que hemos obtenido?

Puedes cargar los datos para resolver este ejercicio con:

In [ ]:
ifprop002 = pd.read_excel("Infer_prop.xlsx", sheet_name="IFprop002")
ifprop002.head()

   Oferta Adquirir
0       1       Si
1       2       Si
2       3       No
3       4       No
4       5       No

### **EJ003**.

Una cadena de inmobiliarias ofrece un plan de venta garantizado. Las casas que han estado en lista y no se han vendido durante seis semanas son adquiridas por la inmobiliaria a un precio determinado. Con el tiempo, el 5% de las casas que son puestas a la venta son adquiridas por la inmobiliaria. Dado que las residencias con piscina resultan más difíciles de vender, se sospecha que con este plan la inmobiliaria adquiere una fracción muy grande de dichas casas. La cadena ha puesto en sus listas 50 de estas residencias con piscina, de las cuales 7 fueron adquiridas con este plan. Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 10% y estable a que conclusión puedes llegar con la información recogida?
* ¿Cómo interpretamos el intervalo de confianza que hemos obtenido?

Puedes cargar los datos para resolver este ejercicio con:

In [ ]:
ifprop003 = pd.read_excel("Infer_prop.xlsx", sheet_name="IFprop003")
ifprop003.head()

   Vivienda Compra
0         1     Si
1         2     Si
2         3     Si
3         4     Si
4         5     Si

### **EJ004**.

El anterior director (por muchos años) de los servicios municipales de la ciudad obtuvo del gobierno federal la subvención solicitada el 50% de las veces que pidió ayuda. Se nombró un nuevo director de servicios municipales de la ciudad quién presento 18 solicitudes de ayuda al gobierno federal durante su primer año. Si 7 de las 18 solicitudes fueron subvencionadas, el concejo municipal quieres saber si hay un cambio en la tasa de resultados positivos bajo la nueva dirección. Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y estable a que conclusión puedes llegar con la información recogida?
* ¿Cómo interpretamos el intervalo de confianza que hemos obtenido?

Puedes cargar los datos para resolver este ejercicio con:

In [ ]:
ifprop004 = pd.read_excel("Infer_prop.xlsx", sheet_name="IFprop004")
ifprop004.head()

   Solicitud Subvencionada
0          1            Si
1          2            Si
2          3            Si
3          4            Si
4          5            Si

### **EJ005.**

El gerente de investigación y desarrollo de una compañía de alimentos comprobó que sólo el 40% de los nuevos productos potenciales que se han sometido a prueba con los clientes son comercializados. Para determinar qué productos han de someterse a prueba por los clientes, el gerente toma 20 nuevos productos potenciales de los cuales 8 fueron comercializados. Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 10% y estable a que conclusión puedes llegar con la información recogida?
* ¿Cómo interpretamos el intervalo de confianza que hemos obtenido?

Puedes cargar los datos para resolver este ejercicio con:

In [ ]:
ifprop005 = pd.read_excel("Infer_prop.xlsx", sheet_name="IFprop005")
ifprop005.head()

   Producto Comerzializado
0         1             Si
1         2             Si
2         3             Si
3         4             Si
4         5             Si

### **EJ006.**

En una encuesta, se descubre que de 2961 residentes en áreas urbanas encuestados, 1697 de ellos ven regularmente un nuevo noticiero de una cadena de televisión, mientras que de 983 residentes en pequeñas localidades rurales, sólo 674 lo ven regularmente. Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y estable a que conclusión puedes llegar con la información recogida?
* ¿Cómo interpretamos el intervalo de confianza que hemos obtenido?

Puedes cargar los datos para resolver este ejercicio con:

In [ ]:
ifprop006 = pd.read_excel("Infer_prop.xlsx", sheet_name="IFprop006")
ifprop006.head()

   Encuestado Residencia Ven_noticias
0           1     Urbana           Si
1           2     Urbana           Si
2           3     Urbana           Si
3           4     Urbana           Si
4           5     Urbana           Si

### **EJ007.**

Un distribuidor minorista de computadoras está tratando de decidir entre dos métodos para dar servicio a los equipos de los clientes. El primer método enfatiza el mantenimiento preventivo; el segundo una respuesta rápida a los problemas. Se atienden dos muestras de clientes, cada una con uno de esos métodos. Después de seis meses, se encuentra que 171 de los 200 clientes atendidos con el primer método están muy satisfechos con el servicio, comparados con los 153 de los 200 clientes atendidos con el segundo método. Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y estable a que conclusión puedes llegar con la información recogida?
* ¿Cómo interpretamos el intervalo de confianza que hemos obtenido?

Puedes cargar los datos para resolver este ejercicio con:

In [ ]:
ifprop007 = pd.read_excel("Infer_prop.xlsx", sheet_name="IFprop007")
ifprop007.head()

   Cliente         Metodo Satisfechos
0        1  Mantenimiento          Si
1        2  Mantenimiento          Si
2        3  Mantenimiento          Si
3        4  Mantenimiento          Si
4        5  Mantenimiento          Si

### **EJ008.**

 El director de medios de información de una agencia publicitaria insertó el mismo anuncio de un banco en dos revistas. En cada una de ellas se colgaron los anuncios de forma semejante. Un mes más tarde, una compañía de investigación de medios encontró que 226 de los 473 lectores encuestados de la primera revista tenía conocimiento de los servicios bancarios que ofrecía el anuncio, al igual que 168 de los 439 lectores de la segunda revista (los lectores de ambas revistas se excluyeron). Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y estable a que conclusión puedes llegar con la información recogida?
* ¿Cómo interpretamos el intervalo de confianza que hemos obtenido?

Puedes cargar los datos para resolver este ejercicio con:

In [ ]:
ifprop008 = pd.read_excel("Infer_prop.xlsx", sheet_name="IFprop008")
ifprop008.head()

   Lectores    Revista Conocimietno servicios
0         1  Revista 1                     Si
1         2  Revista 1                     Si
2         3  Revista 1                     Si
3         4  Revista 1                     Si
4         5  Revista 1                     Si

### **EJ009.**

Se realizan pruebas de fiabilidad muy severas con dos muestras de 30 motores eléctricos para impresoras. De los motores del proveedor 1, pasaron la prueba 22; de los motores del proveedor 2, sólo 16 se aprobaron. Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y estable a que conclusión puedes llegar con la información recogida?
* ¿Cómo interpretamos el intervalo de confianza que hemos obtenido?

Puedes cargar los datos para resolver este ejercicio con:

In [ ]:
ifprop009 = pd.read_excel("Infer_prop.xlsx", sheet_name="IFprop009")
ifprop009.head()

   Motor    Proveedor Fiabilidad
0      1  Proveedor 1         Si
1      2  Proveedor 1         Si
2      3  Proveedor 1         Si
3      4  Proveedor 1         Si
4      5  Proveedor 1         Si

### **EJ010.**


Una gran cadena hotelera está tratando de decidir si convierte más de sus habitaciones en habitaciones para no fumadores. En una muestra aleatoria de 400 huéspedes el año pasado, 166 habían solicitado habitaciones para no fumadores. Este año, 205 huéspedes de una muestra de 380 prefirieron las habitaciones para no fumadores. ¿Recomendaría que la cadena hotelera convierta más habitaciones en habitaciones para no fumadores? Respalde su recomendación probando las hipótesis apropiadas con un nivel de significatividad del 1%. Puedes cargar los datos para resolver este ejercicio con:

In [ ]:
ifprop010 = pd.read_excel("Infer_prop.xlsx", sheet_name="IFprop010")
ifprop010.head()

   Cliente Muestra Fumador
0        1  Pasada      No
1        2  Pasada      No
2        3  Pasada      No
3        4  Pasada      No
4        5  Pasada      No

### **EJ011**

MacroSwift ha lanzado recientemente un nuevo producto de procesamiento de textos y están interesados ​​en determinar si las personas del grupo de 30 a 39 años califican el programa de manera diferente a los miembros del grupo de 40 a 49 años. MacroSwift tomó una muestra aleatoria de 175 personas en el grupo de edad de 30 a 39 años que compraron el producto y encontró que 87 personas calificaron el programa como excelente, y 52 personas comprarían una actualización. También tomaron una muestra de 220 personas en el grupo de edad de 40 a 49 años y encontraron que 94 personas dieron una calificación excelente, y 37 personas que planean comprar una actualización. ¿Existe alguna diferencia significativa en las proporciones de personas en los dos grupos de edad que califican el programa como excelente en un nivel de significatividad del 5%? ¿Se aplica el mismo resultado a proporciones de personas que planean comprar una actualización?

In [ ]:
ifprop011 = pd.read_excel("Infer_prop.xlsx", sheet_name="IFprop011")
ifprop011.head()

   Cliente   Edad Califican Actualizaran
0        1  30-39        Si           Si
1        2  30-39        Si           Si
2        3  30-39        Si           Si
3        4  30-39        Si           Si
4        5  30-39        Si           Si

### **EJ012**

Una central eléctrica alimentada con carbón está considerando dos sistemas diferentes para reducir la contaminación. El primer sistema ha reducido la emisión de contaminantes a niveles aceptables el 68 por ciento de las veces, según lo determinado a partir de 200 muestras de aire. El segundo sistema, más caro, ha reducido la emisión de contaminantes a niveles aceptables el 76 por ciento de las veces, según se determinó a partir de 250 muestras de aire. Si el sistema costoso es significativamente más efectivo que el sistema económico para reducir los contaminantes a niveles aceptables, entonces la administración de la central eléctrica instalará el sistema costoso. ¿Qué sistema se instalará si la dirección utiliza un nivel de significatividad del 1% al tomar su decisión?

In [ ]:
ifprop012 = pd.read_excel("Infer_prop.xlsx", sheet_name="IFprop012")
ifprop012.head()

   Muestra Sistema Reduce
0        1  Barato     Si
1        2  Barato     Si
2        3  Barato     Si
3        4  Barato     Si
4        5  Barato     Si