# <font color="steelblue">260. Ejercicios inferencia estadística sobre medias</font>

**Material desarrollado por los [equipos de trabajo de IA4LEGOS](https://ia4legos.umh.es/)**


**Fecha última edición**: 10/05/2025

**Licencia**: <small><a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br /></small>

No olvides hacer una copia si deseas utilizarlo. Al usar estos contenidos, aceptas nuestros términos de uso y nuestra política de privacidad.

## <font color='steelblue'>Introducción</font>

**Descripción:** Colección de ejercicios sobre variables aleatorias continuas.

In [ ]:
# Cargamos módulos de análisis numérico
import numpy as np          # importamos numpy como np
import pandas as pd         # importamos pandas como pd
import math                 # importamos módulo para cáculos matemáticos

# Cargamos módulos de análisis gráficos
from plotnine import *      # importamos módulo para gráficos con ggplot
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
%config InlineBackend.figure_format = 'retina'

from scipy import stats

Cargamos el repositorio con los bancos de datos

### **EJ001.**

El gerente de una organización para la conservación de la salud ha fijado como objetivo que aquellos pacientes que no acudan por alguna emergencia esperen menos de 30 minutos en ser atendidos. En un control por sondeos, el gerente encuentra que los tiempos de espera de 22 pacientes es de 38.1 minutos. Si la desviación típica de la población es de 10 minutos. Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 1% y establece a que conclusión puedes llegar con la información recogida?
* ¿Cómo interpretamos el intervalo de confianza que hemos obtenido?

Los datos obtenidos son:

In [ ]:
datos = {"Tiempo": [28. , 32.1, 19.7, 26.2, 23.9, 37.2, 37.8, 41.4, 45.3, 32.5, 36. ,
       41.8, 39.7, 49.4, 40. , 43.9, 25.2, 42. , 34.9, 25.6, 55.1, 43.5]}
ifmean001 = pd.DataFrame(datos)
ifmean001.head()

   Tiempo
0    28.0
1    32.1
2    19.7
3    26.2
4    23.9

### **EJ002.**

Una estación de radio quiere controlar el tiempo destinado a los anuncios gratuitos de servicio público. Si hay demasiados anuncios de este tipo, la estación pierde ingresos, si hay muy pocos, la estación pierde puntos en la Comisión Estatal de Comunicaciones. El objetivo es un promedio de 1.5 puntos de estos anuncios por hora. Se ha motado una muestra de 18 horas donde se registran los tiempos (en minutos) destinados a los anuncios gratuitos de servicios públicos. Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?
* ¿Cómo interpretamos el intervalo de confianza que hemos obtenido?

Los datos obtenidos son:

In [ ]:
datos = {"Tiempo": [ 1.2,  0.9, -0.8,  4. , -1.1,  0.4, -1.3,  3.8,  0.8, -0.7, -1. ,
        1.9,  2.1,  1.5,  1.2, -0. ,  2.3,  4.4]}
ifmean002 = pd.DataFrame(datos)
ifmean002.head()

   Tiempo
0     1.2
1     0.9
2    -0.8
3     4.0
4    -1.1

### **EJ003.**

Un responsable de una agencia de seguros utiliza dos talleres distintos para mandar a reparar los automóviles extranjeros que sufren daños por colisión. Para probar si los talleres son competitivos en precio, el ajustador obtiene estimaciones del costo de reparación de ambos talleres para 14 automóviles. Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?
* ¿Cómo interpretamos el intervalo de confianza que hemos obtenido?

Los datos obtenidos son:

In [ ]:
datos = {"Dif_Costes": [0.8, 1.1, 0.5, 0.7, 0.1, 0.4, 0.1, 0.6, 0.8, 0.3, 0.7, 0.3, 1.2,
       0.8, 0.4, 0.6, 0.1, 0.2]}
ifmean003 = pd.DataFrame(datos)
ifmean003.head()

   Dif_Costes
0         0.8
1         1.1
2         0.5
3         0.7
4         0.1

### **EJ004.**

Un distribuidor de papel reciclado coloca contenedores vacios en varios lugares. Los contenedores se recogen (y se reemplazan por otros vacíos) siguiendo distintos itinerarios. En uno de tales trayectos se hace la recolección cada dos semanas. Este plan es aconsejable si la cantidad media de papel reciclado en cada período de dos semanas es mayor que 1600 píes cúbicos. Se han registrado los volúmenes (en pies cúbicos) en 18 puntos de muestreo en el periodo de dos semanas. Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?
* ¿Cómo interpretamos el intervalo de confianza que hemos obtenido?

Los datos obtenidos son:

In [ ]:
datos = {"Volumen": [1616.2, 1912.6, 1663.3, 1450.3, 1449.4, 1812.8, 1797.6, 1703.9,
       1628.7, 1664.7, 1624. , 1832. , 1659.9, 1921.8, 1880.2, 1447. ,
       1797.6, 1449.2]}
ifmean004 = pd.DataFrame(datos)
ifmean004.head()

   Volumen
0   1616.2
1   1912.6
2   1663.3
3   1450.3
4   1449.4

### **EJ005.**

### **EJ006.**

Un auditor piensa que la merma que sufre una cadena de supermercados debido a robos por clientes y los empleados en un mes es del 7%. Para corroborar esta idea toma una muestra de 36 supermercados y estima la media de dicha merma durante un mes. Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?
* ¿Cómo interpretamos el intervalo de confianza que hemos obtenido?

Los datos obtenidos son:

In [ ]:
datos = {"Perdida": [ 4.3,  2.6,  8.6,  3. ,  4.8,  7.7, 10.9,  2.6,  2. ,  6.2, 11.2,
       16. ,  6.2,  5.1,  0.7,  5.7, 11.8,  6.4,  3.9,  7. ,  7.7,  7.7,
        7.9,  6.5,  3.5,  7.8,  3.8,  5.7,  4.5,  3.7,  7.6,  5.5,  6.7,
        4.9, -0.2,  9.2]}
ifmean006 = pd.DataFrame(datos)
ifmean006.head()

   Perdida
0      4.3
1      2.6
2      8.6
3      3.0
4      4.8

### **EJ007.**

Una aerolínea establece un sistema de única fila en la línea de espera de sus ventanillas a fin de reducir el tiempo de espera. En el sistema anterior el tiempo de espera medio era de 6.1 minutos. Se toma una muestra de 14 tiempos de espera. Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?
* ¿Cómo interpretamos el intervalo de confianza que hemos obtenido?

Los datos obtenidos son:

In [ ]:
datos = {"Tiempo": [7.5, 1.7, 6.4, 3.8, 1.8, 6.3, 8. , 0.9, 4.2, 5.7, 0.7, 9.4, 3.5,
       4.7]}
ifmean007 = pd.DataFrame(datos)
ifmean007.head()

   Tiempo
0     7.5
1     1.7
2     6.4
3     3.8
4     1.8

### **EJ008.**

Un fabricante de ropa compra tela en rollos y la corta. En el proceso, cierta cantidad de tela se desperdicia. Con los métodos estándar, el desperdicio es del 9.26%. Un productor de máquinas controladas por computadora le permitió probar una de sus máquinas con una muestra de 762 cortes distintos. Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?
* ¿Cómo interpretamos el intervalo de confianza que hemos obtenido?

Los datos obtenidos son:

In [ ]:
datos = {"Desperdicio": [ 8.31, 10.4 , 10.58,  8.24, 10.03,  9.46,  9.58,  8.95,  6.51,
        8.61,  7.76,  9.5 ,  7.39,  8.19,  8.13,  9.75,  7.93, 10.44,
       10.17,  9.02,  9.77,  8.83,  8.4 , 10.19, 10.43,  9.39,  7.17,
       10.88,  9.4 ,  9.8 ,  9.46,  8.8 , 10.44,  8.2 ,  9.12, 10.55,
        7.51,  9.43,  8.73, 10.17, 10.4 ,  9.89,  8.12,  8.57, 10.15,
        7.85,  6.96,  9.44, 10.16,  8.55, 10.29, 10.59,  9.7 ,  8.95,
        8.76,  9.82,  9.69,  8.89,  9.05, 10.22, 10.16,  6.7 ,  9.27,
        9.72,  9.67,  7.36,  9.22,  8.5 , 10.03,  9.1 ,  8.98,  8.25,
        8.86,  7.5 ,  8.89,  9.38, 10.01,  7.72,  7.4 ,  9.71,  9.23,
        9.19,  8.67,  8.47,  6.79, 10.57,  8.84, 11.66,  7.75,  7.99,
       10.88,  9.84,  8.28,  8.05, 11.14, 10.27,  9.9 ,  7.66,  9.16,
        8.8 ,  8.77,  9.56,  9.44,  7.3 ,  9.16, 11.12,  9.05,  9.49,
        9.04,  8.59,  8.66,  8.89, 10.29,  8.59,  8.55, 10.07, 10.12,
        8.58,  8.18,  9.  ,  8.62,  9.16,  9.42,  7.53,  8.74,  8.17,
        8.96,  8.39,  8.27,  8.07,  9.98,  8.06, 10.41,  9.59,  8.48,
        9.65,  9.28,  8.34,  9.59,  9.81,  8.38,  7.59,  8.69,  9.29,
       10.71,  7.53, 10.04,  7.92,  8.21,  7.19,  8.63,  8.74,  9.1 ,
       11.65,  9.71,  8.77, 10.27,  9.85,  9.21,  7.76,  7.39,  9.6 ,
        9.58,  9.61,  8.36,  9.55, 10.09,  7.8 ,  8.56,  7.49,  9.2 ,
        8.77,  9.67, 10.13,  9.18,  8.87, 10.81, 10.51,  9.93, 10.03,
        9.64,  8.84,  8.32,  9.33,  9.27,  9.57, 10.02,  8.43,  8.71,
        9.82,  9.66,  9.56,  9.12,  9.05,  6.75, 11.22, 10.74, 10.57,
        7.57,  8.93, 11.85,  9.93,  7.12,  8.04,  8.67,  9.34,  7.48,
        9.65, 10.7 ,  8.82,  9.51,  6.62, 11.06, 10.06,  8.5 ,  9.39,
        8.09,  9.07, 10.08,  8.24,  8.36, 10.96,  9.06,  9.5 ,  7.19,
        9.86,  7.71,  8.16,  8.55, 11.31,  8.81,  9.61, 10.4 , 10.13,
        9.48,  9.83, 11.26,  8.95,  8.61,  9.11,  8.65,  9.1 ,  8.26,
        9.54, 10.51,  9.46, 10.35,  8.82,  9.01,  8.26,  6.49,  7.83,
        8.94,  9.1 ,  7.54,  9.7 , 10.51,  8.88,  9.68,  9.4 , 10.36,
        7.9 , 10.97,  9.83,  9.57,  9.02, 10.17,  9.76,  9.26,  9.25,
        9.91,  8.35,  8.59,  8.77,  7.94,  9.09,  9.5 ,  9.36,  8.25,
        9.13,  9.08,  9.35,  8.45,  9.79, 10.22, 10.61,  9.54,  7.56,
        7.46, 10.74, 11.35,  7.54,  9.87, 10.2 , 10.63, 11.8 ,  8.79,
        7.54,  8.22,  9.28,  9.76, 10.46, 10.4 ,  7.8 , 10.72, 10.74,
        8.71,  8.66, 11.21,  9.96,  8.9 ,  9.92,  8.48,  8.23,  9.  ,
        8.55,  9.97,  9.15,  7.31,  9.01,  7.08,  7.83,  7.27,  9.08,
        9.45,  9.08,  8.  ,  8.13,  8.53,  9.55,  7.89,  9.93, 10.59,
        9.96,  8.51,  9.05,  9.21, 10.8 ,  8.38,  7.46,  7.83, 10.9 ,
        8.19, 10.2 ,  8.85,  8.32,  8.75,  7.55,  9.37,  8.56,  8.41,
        8.82,  7.85,  8.61,  9.73,  9.25, 10.68,  8.8 ,  8.92,  9.92,
        7.5 , 11.3 , 10.24,  6.39, 12.1 ,  9.81,  7.74,  9.77,  7.37,
        8.7 , 11.01,  9.07,  8.19,  7.74,  8.78,  9.4 ,  8.42, 10.34,
        9.48, 10.47,  9.37,  7.46,  8.27,  8.41,  9.34,  8.37,  9.97,
        8.62,  9.59,  9.33,  8.7 ,  9.27,  8.91,  9.28,  9.56, 10.41,
       10.07,  9.68,  9.17,  9.46,  9.73,  8.15,  8.49,  8.76,  9.45,
        7.08,  9.98,  8.3 , 10.56,  8.22, 10.98,  8.12,  8.1 ,  9.53,
       10.49, 10.48,  8.08,  9.25,  9.79,  9.13, 10.17,  7.8 ,  9.02,
        7.93,  8.53,  8.78,  7.58,  8.69,  6.86,  6.59,  7.76,  9.71,
        8.94, 10.95,  8.85,  9.8 ,  8.84,  8.19, 10.1 ,  7.21,  8.99,
        9.23,  8.19,  8.44,  9.11, 10.36,  8.61,  9.24,  9.13,  9.53,
        9.38,  9.46, 11.31,  8.88,  6.97, 10.71,  8.39, 10.1 ,  7.6 ,
        8.87,  9.07,  8.01,  9.82,  8.68,  9.08,  9.76,  7.89,  8.57,
       10.24,  8.47,  8.04,  8.73,  9.47,  8.45, 11.52,  8.95, 11.82,
        8.61,  9.21,  9.14,  9.26,  7.63,  9.36, 10.04, 10.14, 11.19,
       10.01,  8.58,  9.21,  8.87, 10.95,  6.67,  7.81,  9.09, 10.26,
        9.74,  7.66,  8.94,  8.14,  8.24,  9.29,  9.63,  6.08,  8.68,
        9.1 , 10.63,  8.6 ,  8.2 ,  8.53,  9.46,  8.65,  9.61,  9.56,
        7.49,  9.04,  9.15,  9.98, 11.03,  9.15, 11.24, 10.46,  9.68,
        8.98,  7.88,  8.19,  8.26,  9.8 , 11.2 ,  9.77,  7.3 ,  9.65,
       10.85, 10.18,  9.04,  8.64,  9.5 ,  6.93,  8.85,  9.41,  9.29,
        9.99,  8.62,  8.37,  8.46,  9.73,  9.28,  8.  , 11.52,  8.08,
       10.05, 10.77,  9.34,  9.58,  9.3 ,  8.61,  9.03,  8.57,  9.3 ,
        7.85,  8.73,  8.45,  9.11,  8.45,  8.14,  8.96,  8.11, 11.2 ,
        8.83,  7.57,  9.94,  8.88, 10.15, 10.31,  6.87,  9.31,  9.59,
        6.9 , 10.3 ,  9.27,  9.86,  8.54,  7.73,  8.47,  8.47,  7.84,
        7.8 ,  9.16,  9.75,  8.91,  7.19, 10.52,  8.24,  9.67,  9.1 ,
       11.15,  8.66,  8.68,  7.49, 10.72, 10.35,  8.76,  8.84,  7.54,
        8.68,  9.9 ,  9.57,  8.68, 10.8 ,  8.91,  9.07,  7.39,  9.02,
        9.3 ,  6.75,  8.97, 10.15, 11.18,  9.42, 11.05,  8.45,  8.43,
       10.64,  9.16,  8.93,  8.38,  9.57,  7.82,  9.95,  9.06, 10.15,
       10.05,  9.07,  8.92,  7.96,  8.92,  9.96,  7.01, 10.53, 10.14,
       10.22,  9.11,  9.65, 10.41, 10.19, 10.52,  9.76,  8.95,  9.23,
       10.49,  6.75,  9.18, 10.45,  9.02,  8.52, 10.98,  8.94, 10.59,
        8.07,  9.15,  9.1 ,  9.36,  7.75, 10.77,  8.96,  9.86,  9.34,
       10.06, 10.78,  9.05,  7.84,  7.2 , 10.54,  8.74,  9.3 , 11.59,
       11.67,  9.42,  9.15,  8.25, 10.97,  9.55,  9.57,  8.94,  9.84,
        7.92,  7.69,  8.56,  8.8 , 10.2 , 10.99,  9.02,  9.59,  8.99,
        8.68,  7.44,  6.89,  9.05,  8.83,  7.37, 10.08,  8.41, 10.88,
       10.78,  9.09,  8.1 ,  9.69, 10.63,  9.83, 11.24,  8.83,  8.02,
        9.72,  8.18, 10.03,  9.3 ,  7.29, 10.46,  6.39,  9.07,  8.86,
        9.65, 10.69,  9.91,  9.41,  8.86,  9.08,  8.89,  8.53, 11.43,
        7.62,  9.4 ,  9.32,  9.04, 10.5 , 10.4 , 10.18, 10.53, 10.01,
        7.35,  8.35,  9.77,  9.27,  8.52,  8.52, 11.4 , 10.25,  8.88,
        9.03,  8.39,  8.74,  8.39,  9.41,  8.59, 10.74,  9.9 ,  8.86,
       10.94,  5.92,  8.55, 10.07, 10.36,  8.21]}
ifmean008 = pd.DataFrame(datos)
ifmean008.head()

   Desperdicio
0         8.31
1        10.40
2        10.58
3         8.24
4        10.03

### **EJ009.**

En una línea de envasado se llenan tarros de jugo de tomate con un contenido nominal de 32 onzas y una media real de 32.20 onzas. El proceso debería tener una desviación estándar menor que 0.15 onzas por tarro (una desviación mayor conduce a tener muchos tarros con un peso deficiente y otros con un peso excesivo). Para probar el proceso se toman regularmente muestras de 61 tarros. Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?
* ¿Cómo interpretamos el intervalo de confianza que hemos obtenido?

Los datos obtenidos son:

In [ ]:
datos = {"Peso": [32.19, 32.05, 32.21, 32.56, 32.37, 32.21, 32.09, 32.49, 32.41,
       32.32, 32.27, 32.16, 32.11, 32.04, 32.28, 32.21, 32.25, 32.22,
       32.25, 32.23, 32.21, 32.47, 32.25, 32.61, 32.27, 32.36, 32.28,
       32.3 , 32.09, 32.16, 32.26, 32.12, 32.18, 32.16, 32.02, 32.44,
       32.29, 32.56, 32.34, 32.48, 32.18, 32.41, 32.17, 32.51, 32.28,
       32.2 , 32.32, 31.97, 32.27, 32.22, 32.41, 32.15, 32.45, 32.09,
       32.44, 32.28, 32.28, 32.42, 32.27, 32.18, 31.87]}
ifmean009 = pd.DataFrame(datos)
ifmean009.head()

    Peso
0  32.19
1  32.05
2  32.21
3  32.56
4  32.37

### **EJ010.**

El departamento de I+D de una empresa que fabrica cereal inflado ensaya dos procedimientos de mantenimiento preventivo con dos de las pistolas utilizadas en el procesamiento para mantener la calidad del producto y reducir el tiempo de horas de operación. Se registra el número de horas de operación entre los periodos de paro total. Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?

Los datos obtenidos son:

In [ ]:
datos ={"horas":[ 28.77,  21.48,  56.11,  42.21,  20.85,  46.74,  31.21,  23.35,
        79.6 ,  57.72,  87.37,  38.11,  20.84,  61.71,  32.06, 117.94,
        -8.39, 124.74,  17.42,  56.17,  60.48, 151.37,  29.7 ,  54.1 ,
        77.42,  67.05,  63.44,  51.25,  35.78, 115.56,  47.97,  63.64,
        41.27,  21.57,  45.37,  38.5 ,  95.52,  51.33,  33.6 ,  25.41,
       127.79,  26.46,  76.41,  53.08,  66.59,  54.16,  32.77,  54.79,
         4.02,  79.05,  93.1 ,  43.47,  -3.47,  22.08, 146.44,  80.15,
       135.41, 139.8 ,  41.45,  58.23,  51.53, 167.3 , -19.09,  40.82,
        59.34,  34.97,  30.76,  48.23,  67.98,  45.89,  92.04,  43.69,
        16.29,  95.75, 143.77,  62.52,  29.35,  71.67,  47.72,  45.03,
        59.4 ,  58.67,  52.75,  35.84,  84.29, 112.49,  32.69,  41.88,
        47.6 ,  49.85,  70.65,  23.68,  98.83,  71.92,  84.4 ,  26.96,
        26.46, 106.08, 126.66,  62.95,  46.93,  68.79,  16.48, 140.96,
        25.94,   7.83,  21.34,  54.04, 140.99,  76.37,  11.29,  22.36,
        18.92, 114.57,  33.22, 118.6 ,  59.93,  71.79,  63.09,  43.97,
        77.32,  90.35,  20.49,  46.99,  68.53,  54.28,  46.3 ,  76.87,
                  76.46, 107.33, 109.74, 123.11, 114.42,  98.47,
        25.98,  30.46,  73.53,   3.66, 114.1 ,  87.58, 103.74, -18.34,
        82.35,  13.22,  60.83, 118.87, 154.65,  40.8 , 114.71,  78.41,
        74.3 ,  60.57,  88.21, 104.37,  91.96,  61.94,  33.53,  74.8 ,
       140.31,  87.88,  35.21,  49.27, 126.5 ,  67.59,  49.34,  95.68,
        46.04,   6.42,  21.01, 107.03,  36.26,  40.93,  50.88,  78.76,
        70.38, -48.66,  74.66,  96.89,  47.73,  62.14,  65.04, 137.5 ,
         2.68,  16.94, 105.73,   0.76,  33.13,  61.  ,  15.49,  83.71,
        70.77, 109.06,  60.77,  35.64, -22.88,  28.73,  -5.32,  16.72,
        49.81,  35.63,  91.54,  21.16,  70.83,  31.75,  89.01, 107.43,
        11.45,  31.76,  23.96,  26.66,   0.32,  96.57,  82.77, 102.92,
        86.09, 107.65,  75.12,  81.87,  69.31,  10.45,  44.68,  67.02,
        71.26,  68.36, -16.51,  44.47,  66.28,  66.46,  20.93,  56.13,
        63.62,  38.02,   3.37,  24.33,  47.9 ,  66.05,  41.64,  34.26,
       120.4 , 138.38,  12.74,  58.7 ,  33.01,  24.34,   8.54, 108.28,
        54.8 ,  29.06,   1.94, -26.91,  40.04,  63.23,  28.53, 104.81,
       101.75,  51.93,   6.84,  94.39,  27.39,  83.17,  59.88, 101.64,
         9.23,  70.26, 109.2 , 129.06, -52.73,   0.79, -26.21, 114.77,
        79.92,  84.4 ,   7.98,  31.18,  56.51, 117.47, 150.47,  96.81,
        56.99,  11.34,  40.08],
        "Maquina": ['Uno', 'Uno', 'Uno', 'Uno', 'Uno', 'Uno', 'Uno', 'Uno',
            'Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno',
  'Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno',
  'Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno',
  'Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno',
  'Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno',
  'Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno',
  'Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno',
  'Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno',
  'Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno',
  'Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno',
  'Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Uno','Dos',
  'Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos',
  'Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos',
  'Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos',
  'Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos',
  'Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos',
  'Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos',
  'Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos',
  'Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos',
  'Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos',
  'Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos',
  'Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos',
  'Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos',
  'Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos',
  'Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos','Dos']}
ifmean010 = pd.DataFrame(datos)
ifmean010.head(5)

   horas Maquina
0  28.77     Uno
1  21.48     Uno
2  56.11     Uno
3  42.21     Uno
4  20.85     Uno

### **EJ011.**

Un mayorista especializado en productos farmacéuticos incurre en gastos considerablemente elevados para "documentar" cada pedido. En un esfuerzo por reducir el tiempo requerido, se ha programado una minicomputadora para enumerar los artículos de manera eficiente. Se prueban dos programas basados en diferentes principios de eficiencia. Se corre un centenar de pedidos con cada uno de ellos y se registra el tiempo total de trabajo por orden. Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?

Los datos obtenidos son:

In [ ]:
datos ={"Tiempo": [2.59,  1.18,  1.68,  0.24,  1.4 ,  1.79,  0.91,  1.65,  1.35,
        2.81, -0.14, -0.31,  0.48,  0.85,  1.75,  1.81,  0.86,  2.06,
        4.09,  0.47,  0.71,  2.5 ,  1.02,  0.35,  0.69,  0.74,  1.98,
        2.04,  0.05,  0.7 ,  0.94,  1.62,  2.69,  1.12,  2.42,  1.12,
        1.96, -0.36,  1.49,  3.35,  1.24,  2.43, -0.29,  0.72,  1.64,
        1.4 ,  3.37,  0.96,  0.98,  0.86,  0.99,  0.98,  1.17,  0.79,
        2.53,  0.51,  2.92,  0.85,  2.39,  1.83,  2.04,  2.32,  0.5 ,
        0.85,  2.51,  0.13,  2.96,  1.37,  1.29,  2.46,  1.59,  2.14,
        2.57,  2.51,  1.95,  2.95,  1.99,  1.85,  0.98,  1.39,  1.95,
        1.5 ,  3.36,  1.81,  0.67,  3.73,  2.12,  1.99,  0.68,  3.28,
        1.31,  2.72,  1.69,  2.04,  2.43,  1.47,  3.39, -0.86,  0.72,
        1.11, 3.19, 1.62, 2.05, 2.48, 2.65, 0.19, 2.5 , 1.68, 1.11, 1.69, 2.4 ,
       0.7 , 0.47, 1.91, 1.72, 2.11, 1.84, 0.58, 3.63, 2.58, 2.63, 2.05,
       1.76, 2.84, 2.42, 0.68, 1.82, 2.52, 1.48, 0.85, 2.34, 3.31, 2.35,
       1.02, 0.47, 0.77, 0.12, 2.74, 2.  , 2.9 , 0.99, 1.17, 3.97, 4.44,
       1.7 , 3.32, 2.31, 3.44, 0.85, 1.67, 0.99, 4.09, 1.84, 2.03, 1.06,
       1.38, 0.81, 1.61, 2.24, 3.  , 0.93, 2.33, 2.49, 2.99, 1.82, 2.42,
       2.21, 2.94, 2.17, 0.22, 1.73, 1.09, 1.44, 1.54, 3.48, 1.61, 2.42,
       1.56, 1.88, 1.63, 1.28, 3.31, 3.46, 2.45, 1.09, 1.24, 3.  , 3.31,
       1.64, 1.95, 0.5 , 0.96, 2.7 , 1.61, 3.31, 1.15, 2.21, 1.24, 2.12,
       1.4],
        "Programa": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
                     2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]}
ifmean011 = pd.DataFrame(datos)
ifmean011.Programa.replace({1: "Uno", 2: "Dos"},inplace=True)
ifmean011.head(5)

   Tiempo Programa
0    2.59      Uno
1    1.18      Uno
2    1.68      Uno
3    0.24      Uno
4    1.40      Uno

### **EJ012.**

Dos agencias suministran trabajadores temporales para labores ligeras. Ambas agencias aplican a sus trabajadores una prueba de destreza que deben superar. En un momento particular se obtiene la información  de las puntuaciones de destreza para cada una de las empresas. Se desea comparar la destreza de los trabajadores de amas empresas. Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?

Los datos obtenidos son:

In [ ]:
datos ={"Puntuacion": [72.01, 61.25, 71.51, 54.74, 99.44, 76.5 , 73.71, 69.31,
                       66.22, 70.08, 95.74, 64.16, 75.25, 70.91, 86.72, 76.54, 66.49,
       87.13, 73.47, 89.32],
        "Agencia": ["K","K","K","K","K","K","K","K",
                     "R","R","R","R","R","R","R","R","R","R","R","R"]}
ifmean012 = pd.DataFrame(datos)
ifmean012.head(5)

   Puntuacion Agencia
0       72.01       K
1       61.25       K
2       71.51       K
3       54.74       K
4       99.44       K

### **EJ013.**

Una compañía de taxis quiere probar dos programas para mejorar el rendimiento de sus choferes. En el programa A, se les asigna un rendimiento objetivo a los choferes y reciben modestos bonos cuando lo superan. En el programa B, a los choferes se les otorga una cuota mensual máxima de gasolina; si ésta se agota, el chofer deberá pagar de su bolsillo la gasolina extra. Todos los taxis son de modelo estándar y se les da el mismo mantenimiento. Después de tres meses, se calcula el rendimiento de cada chofer en kilómetros recorridos por litro de combustible. Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?

Los datos obtenidos son:

In [ ]:
datos ={"Rendimiento": [15.9, 17.5, 19.1, 16.9,18.3,17.3,17,16.2,16.8,17.1,
                     16.1,15.8,15.3,16.5,14.9,15.5,16.4,16,16.7,17.2],
        "Programa": ["A","A","A","A","A","A","A","A","A","A",
                     "B","B","B","B","B","B","B","B","B","B"]}
ifmean013 = pd.DataFrame(datos)
ifmean013.head(5)

   Rendimiento Programa
0         15.9        A
1         17.5        A
2         19.1        A
3         16.9        A
4         18.3        A

### **EJ014.**

Una compañía tiene una política generosa, pero bastante complicada, relativa a los bonos de fin de año para el personal de dirección de rango bajo. El factor clave de la política es el juicio subjetivo de contribución a las metas de la empresa. El director de personal toma una muestra de 24 mujeres y 36 hombres que desempeñan cargos gerenciales para ver si hay diferencias en los bonos, expresadas como porcentaje de salario anual. Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?

Los datos obtenidos son:

In [ ]:
datos ={"Bono": [11.62,  5.9 ,  8.03,  8.62,  7.87,  6.38,  9.53,  8.12,  8.7 ,
        8.08,  9.11,  7.8 ,  7.69,  9.83,  8.25,  6.9 ,  8.34,  8.73,
        9.94,  9.37, 10.34,  9.79,  7.86,  7.81, 8.72,  9.95,  9.01,  8.6 ,
        9.57,  8.45,  9.96, 11.61, 10.25, 8.91, 11.81,  9.2 , 10.47, 10.3 ,
        10.25,  8.01, 10.28,  9.51, 8.88,  8.7 ,  9.82, 10.43,  9.46, 10.43,
        11.01, 10.67, 10.49, 8.82,  9.92, 10.77, 10.24,  9.19,  9.42, 10.38,
        11.17, 10.03],
        "Sexo": ["Mujer","Mujer","Mujer","Mujer","Mujer","Mujer","Mujer","Mujer",
                 "Mujer","Mujer","Mujer","Mujer","Mujer","Mujer","Mujer","Mujer",
                 "Mujer","Mujer","Mujer","Mujer","Mujer","Mujer","Mujer","Mujer",
                 "Hombre","Hombre","Hombre","Hombre","Hombre","Hombre","Hombre",
                 "Hombre","Hombre","Hombre","Hombre","Hombre","Hombre","Hombre",
                 "Hombre","Hombre","Hombre","Hombre","Hombre","Hombre","Hombre",
                 "Hombre","Hombre","Hombre","Hombre","Hombre","Hombre","Hombre",
                 "Hombre","Hombre","Hombre","Hombre","Hombre","Hombre","Hombre",
                 "Hombre"]}
ifmean014 = pd.DataFrame(datos)
ifmean014.head(5)

    Bono   Sexo
0  11.62  Mujer
1   5.90  Mujer
2   8.03  Mujer
3   8.62  Mujer
4   7.87  Mujer

### **EJ015.**

Block Enterprises, un fabricante de chips para computadoras, está en el proceso de decidir si reemplazará su actual línea de ensamblaje semiautomática por una línea de ensamblaje totalmente automatizada. Block ha recopilado algunos datos de prueba preliminares sobre la producción de chips por hora, que aparecen a continuación. A la empresa le gustaría saber si debería actualizar su línea de ensamblaje, es decir si la producción en la línea automática es mejor que en la semiautomática. Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?

Los datos obtenidos son:

In [ ]:
datos ={"Produccion": [162.3 , 177.18, 138.39, 204.02, 194.29, 232.62, 203.38, 230.67,
       173.05, 237.23, 212.88, 220.48, 154.56, 175.96, 221.3 , 219.56,
       233.12, 231.13, 254.76, 188.48, 198.06, 147.44, 195.65, 224.1 ,
       129.45, 226.74, 251.39, 173.62, 211.89, 241.47, 190.44, 195.58,
       172.97, 186.01, 218.43, 202.94, 244.95, 244.67, 155.71, 208.3 ,
       215.56, 170.66, 159.83, 176.9 , 244.59, 213.6 , 170.4 , 181.04,
       171.7 , 180.83, 197.92, 215.38, 218.23, 210.43, 201.01, 175.8 ,
       220.41, 215.99, 172.5 , 195.18, 206.2 , 172.26, 302.85, 236.26,
       188.38, 224.48, 194.88, 224.52, 194.35, 197.09, 153.5 , 183.96,
       179.4 , 198.1 , 198.93, 280.69, 230.92, 199.54, 219.32, 209.5 ,
       117.77, 181.5 , 184.61, 154.68, 190.16, 142.62, 195.02, 217.46,
       198.43, 218.7 , 141.91, 201.26, 188.58, 203.01, 242.34, 114.42,
       181.31, 201.15, 187.08, 188.75, 192.95, 121.78, 193.22, 189.77,
       235.56, 213.28, 178.88, 189.16, 156.99, 243.05, 143.17, 200.49,
       260.35, 156.53, 174.21, 197.69, 182.58, 169.73, 146.71, 216.57,
       206.25, 209.93, 153.51, 180.  , 200.22, 204.47, 178.31, 202.61,
       168.37, 178.63, 186.12, 228.47, 231.  , 214.36, 283.73, 149.96,
       220.48, 194.35, 138.98, 178.69, 260.08, 195.74, 214.17, 204.67,
       177.88, 213.81, 183.5 , 248.81, 237.04, 183.68,
      204.88, 218.15, 164.23, 193.07, 194.56, 229.75, 207.66, 196.15,
       184.77, 185.41, 235.56, 230.46, 148.4 , 215.15, 188.68, 261.98,
       254.34, 190.07, 230.83, 182.84, 174.97, 158.39, 158.29, 236.08,
       257.89, 214.21, 166.5 , 244.7 , 237.75, 180.32, 180.88, 206.38,
       186.48, 184.84, 253.41, 225.41, 242.5 , 193.1 , 248.12, 218.05,
       170.51, 175.91, 221.54, 186.19, 210.52, 183.76, 170.07, 156.39,
       208.8 , 122.42, 184.79, 237.19, 205.26, 180.3 , 280.04, 164.7 ,
       248.15, 191.55, 204.38, 204.52, 221.95, 256.64, 236.27, 192.6 ,
       269.26, 189.01, 182.67, 197.17, 162.1 , 207.14, 202.05, 205.09,
       178.11, 205.49, 166.72, 213.81, 235.23, 221.8 , 176.82, 229.71,
       215.53, 241.75, 168.54, 234.14, 197.49, 157.36, 175.47, 178.78,
       207.89, 263.67, 206.57, 232.  , 228.3 , 163.18, 198.5 , 204.24,
       192.96, 246.31, 245.43, 202.7 , 257.59, 211.54, 181.44, 217.55,
       201.04, 216.5 , 215.08, 169.5 , 221.93, 160.37, 254.86, 207.5 ,
       204.55, 240.88, 218.02, 196.22, 195.29, 183.68, 227.31, 218.06,
       165.01, 187.95, 170.64, 200.89, 165.41, 184.74, 205.48, 213.31,
       272.62, 232.67, 174.27, 158.46, 267.56, 245.07, 213.64, 197.91,
       259.06, 201.84, 172.52, 196.3 , 236.47, 186.18, 205.97, 207.64,
       234.38, 209.42, 232.13, 245.97, 181.33, 210.49, 221.74, 188.63,
       226.16, 205.91, 220.63, 159.75, 234.64, 229.67, 202.02, 209.86,
       185.09, 204.94, 164.48, 220.26, 195.37, 176.64, 164.49, 210.53,
       240.75, 233.1 , 208.52, 200.44, 167.8 , 191.46, 182.81, 169.75,
       261.17, 236.3 , 184.44, 150.1 , 191.92, 253.66, 128.76, 142.02,
       226.2 , 211.43, 225.97, 162.76, 179.53, 215.68, 282.46, 212.73,
       219.75, 243.17, 218.37, 193.47, 156.32, 212.44, 215.67, 189.04],
      "Linea": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2]}
ifmean015 = pd.DataFrame(datos)
ifmean015.Linea.replace({1: "Semiautomática", 2: "Automática"},inplace=True)
ifmean015.head(5)

   Produccion           Linea
0      162.30  Semiautomática
1      177.18  Semiautomática
2      138.39  Semiautomática
3      204.02  Semiautomática
4      194.29  Semiautomática

### **EJ016.**

Dos laboratorios de investigación han producido de forma independiente medicamentos que brindan alivio a quienes padecen artritis. El primer fármaco se probó en un grupo de 90 pacientes mientras que el segundo se probo en 80 pacientes. La variable medida es el tiempo de alivio (en horas) tras la toma del medicamento. Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?

Los datos obtenidos son:

In [ ]:
datos ={"Tiempo": [9.51,  9.84, 10.  ,  9.8 ,  9.11,  8.74,  7.86,  6.77,  8.58,
        2.92,  7.04,  6.29,  8.95,  7.37,  8.77, 11.31,  7.46,  6.87,
        6.91,  6.7 ,  7.71,  7.71,  6.16,  8.86, 10.36,  6.18,  8.22,
        8.68,  7.66, 10.47,  4.29, 11.48,  6.65,  9.37,  8.13, 10.85,
        6.66,  7.77,  7.41,  7.85, 10.19,  9.6 ,  9.41,  7.19, 10.11,
        9.67,  7.49,  9.57,  8.57, 11.01,  6.52,  8.67, 10.16, 10.47,
        4.66, 10.56, 12.64,  9.03,  8.16,  7.81,  8.91, 10.82,  9.54,
        7.35,  6.12,  7.6 ,  7.67,  2.51,  6.04,  6.23,  7.96, 12.09,
       11.71, 10.74,  7.39,  8.37,  7.47,  8.59, 10.75,  8.55,  6.86,
        6.34,  8.43, 10.74,  8.8 ,  6.95,  9.7 ,  6.01,  5.6 ,  6.39,
                   6.31,  9.83, 12.28,  8.13,  5.21,  5.25,  9.72, 11.91,  9.37,
        7.35,  8.44,  7.52,  8.03,  8.69,  8.4 ,  9.94,  4.49,  6.78,
       10.67, 11.86,  6.38,  8.18, 11.75,  9.22,  3.25, 13.03,  5.17,
        9.07,  8.34,  9.59,  7.22, 10.12,  3.52,  8.27,  8.46, 11.46,
        8.28,  7.6 ,  8.95,  6.84,  7.65,  9.61,  8.06,  8.56,  5.74,
        5.88,  9.25,  7.85,  6.58,  8.32,  5.59,  3.22,  5.75,  6.78,
        7.69,  9.07,  6.84,  9.45,  9.97,  5.44,  6.09,  9.03,  6.71,
        7.94,  5.54,  6.5 ,  9.15,  7.39, 10.81,  4.91,  6.03,  8.11,
        6.93,  7.1 ,  4.  ,  4.18,  8.55, 12.33,  8.66,  2.84],
      "laboratorio": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]}
ifmean016 = pd.DataFrame(datos)
ifmean016.laboratorio.replace({1: "Lab 1", 2: "Lab 2"},inplace=True)
ifmean016.head(5)

   Tiempo laboratorio
0    9.51       Lab 1
1    9.84       Lab 1
2   10.00       Lab 1
3    9.80       Lab 1
4    9.11       Lab 1

### **EJ017.**

La tienda BullsEye Discount siempre se ha enorgullecido de su servicio al cliente. La tienda espera que todas las tiendas BullsEye brinden el mismo nivel de servicio de una región a otra, por lo que han encuestado a algunos clientes y les ha preguntado sobre su satisfacción general. En la región Sudeste se entrevistaron a 97 clientes, mientras que en la región Noreste se entrevisto a 84 clientes. Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?

Los datos obtenidos son:

In [ ]:
datos ={"Satisfaccion": [8.71,  9.99,  9.4 ,  7.74,  7.94,  9.61,  8.42,  8.76,  8.18,
        8.62,  9.53,  8.92,  7.93,  9.38,  9.41,  9.74,  8.22,  9.07,
        8.63, 10.48,  9.32,  7.99,  7.62,  8.6 ,  9.4 ,  9.12,  8.74,
        9.12,  8.79,  9.54,  9.06,  8.4 ,  8.61,  8.91,  7.14,  8.42,
        9.26,  8.32,  8.08,  8.41,  9.57,  8.37,  8.95,  8.24,  9.12,
        9.1 ,  8.93,  8.59,  8.61,  8.  ,  8.7 ,  8.82,  9.95,  8.22,
        8.62,  9.24,  9.05,  8.98,  8.86,  7.81,  9.48,  8.51, 10.4 ,
        9.93,  9.19,  9.57,  8.56,  7.73,  9.15, 10.36,  9.32,  8.95,
        9.02,  8.59,  9.9 ,  8.33,  8.88,  8.6 ,  8.38,  8.76,  8.92,
        8.89,  8.35,  9.25,  8.22,  9.17,  9.17,  8.29,  8.33,  7.89,
        7.43,  8.32,  7.98, 10.09,  8.91,  9.49,  8.5,
        8.78,  9.26,  8.45,  9.52,  9.91,  8.22,  8.45,  8.99,  9.41,
        8.13,  8.88,  9.37,  8.6 ,  9.13,  9.66,  9.72,  8.74,  8.4 ,
        8.63,  8.22,  9.16,  8.12,  8.46,  8.86,  9.01,  8.51,  9.1 ,
        8.73,  8.97,  9.01,  8.81,  9.66,  9.33,  8.88,  8.94,  9.4 ,
        8.62,  8.97,  8.97,  8.68,  8.28,  8.73,  8.77,  9.36,  9.29,
        9.32,  9.82,  9.68,  8.34, 10.19,  8.78, 10.09,  8.04,  7.91,
        8.28,  9.6 ,  7.78,  9.94,  9.19,  9.33,  8.  ,  9.21,  9.25,
        9.61,  8.25,  9.77,  9.02,  9.44, 10.25,  7.54,  7.52,  9.15,
        9.75,  9.51,  8.38,  9.88,  8.42, 10.02,  9.19,  9.61,  8.62,
        8.91,  9.52,  8.51],
      "Region": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]}
ifmean017 = pd.DataFrame(datos)
ifmean017.Region.replace({1: "Sudeste", 2: "Noreste"},inplace=True)
ifmean017.head(5)

   Satisfaccion   Region
0          8.71  Sudeste
1          9.99  Sudeste
2          9.40  Sudeste
3          7.74  Sudeste
4          7.94  Sudeste

### **EJ018.**

Additives-R-Us ha desarrollado un aditivo para mejorar la eficiencia del combustible en camiones que transportan cargas muy pesadas. Probaron el aditivo seleccionando al azar 18 camiones y dividiéndolos en 9 pares. En cada par, ambos camiones transportaron el mismo tipo de carga por la misma carretera, pero sólo un camión utilizó combustible con el nuevo aditivo. Diferentes parejas siguieron diferentes rutas y transportaron diferentes cargas. Las eficiencias de combustible resultantes (en millas por galón) se detallan a continuación. Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?

Los datos obtenidos son:

In [ ]:
datos ={"Eficiencia": [5.7,6.1,5.9,6.2,6.4,5.1,5.9,6.0,5.5,
                       6.0,6.2,5.8,6.6,6.7,5.3,5.7,6.1,5.9],
        "Par": [1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9],
      "Aditivo": ["Normal", "Normal","Normal","Normal","Normal","Normal",
                  "Normal","Normal","Normal", "Mejorado","Mejorado",
                  "Mejorado","Mejorado","Mejorado","Mejorado","Mejorado",
                  "Mejorado","Mejorado"]}
ifmean018 = pd.DataFrame(datos)
ifmean018.head(5)

   Eficiencia  Par Aditivo
0         5.7    1  Normal
1         6.1    2  Normal
2         5.9    3  Normal
3         6.2    4  Normal
4         6.4    5  Normal

### **EJ019.**

Para el banco de datos `diabetes` definido en el cuaderno de bancos de datos estamos interesado en conocer si los niveles de glucosa (`Glucose`) y el índice de masa corporal (`BMI`) son diferentes para los pacientes diagnósticados con diabetes (`diabetes` = 1) frente a los no diabéticos (`diabetes` = 0). Para ambas variables se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?

Podemos cargar los datos con:

In [ ]:
url = 'https://raw.githubusercontent.com/jmsocuellamos/DataPython/main/diabetes.csv'
diabetes = pd.read_csv(url)
diabetes.Outcome.replace({1: "Diabético", 0: "No diabético"}, inplace=True)
diabetes

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,Diabético
1,1,85,66,29,0,26.6,0.351,31,No diabético
2,8,183,64,0,0,23.3,0.672,32,Diabético
3,1,89,66,23,94,28.1,0.167,21,No diabético
4,0,137,40,35,168,43.1,2.288,33,Diabético
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,No diabético
764,2,122,70,27,0,36.8,0.340,27,No diabético
765,5,121,72,23,112,26.2,0.245,30,No diabético
766,1,126,60,0,0,30.1,0.349,47,Diabético
767,1,93,70,31,0,30.4,0.315,23,No diabético

### **EJ020.**

Para el banco de datos `avocado` definido en el cuaderno de bancos de datos estamos interesado en conocer si el precio medio (`AveragePrice`) y número total de avocados vendidos (`Total Volume`) es superior en los de tipo orgánico (`type` = organic) frente a los de tipo convencional (`type` = conventional). Para ambas variables se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?


Podemos cargar los datos con:

In [ ]:
# LECTURA
url = 'https://raw.githubusercontent.com/jmsocuellamos/DataPython/main/avocado.csv'
avocado = pd.read_csv(url)
avocado = avocado.drop(columns="Unnamed: 0")
avocado.head(5)

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany

### **EJ021.**

Para el banco de datos `fbi` definido en el cuaderno de bancos de datos estamos interesado en conocer si la edad de la víctima (`Victim_Age`) es diferente en función del sexo del perpetrador (`Perpretrator_Sex`). Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?


Podemos cargar los datos con:

In [ ]:
url = 'https://raw.githubusercontent.com/jmsocuellamos/DataSeg/master/FBI.csv'
fbi = pd.read_csv(url, sep =";") # en este caso el separador de campos es el ; en lugar de ,
fbi.head(5)

,Record_ID,Agency_Code,Agency_Name,Agency_Type,City,State,Year,Month,Incident,Crime_Type,...,Victim_Ethnicity,Perpetrator_Sex,Perpetrator_Age,Perpetrator_Race,Perpetrator_Ethnicity,Relationship,Weapon,Victim_Count,Perpetrator_Count,Record_Source
0,498756,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,2006,February,1,Murder or Manslaughter,...,Unknown,Male,42.0,White,Unknown,Stranger,Firearm,0.0,1.0,FBI
1,498757,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,2006,February,2,Murder or Manslaughter,...,Unknown,Male,19.0,White,Unknown,Friend,Handgun,0.0,0.0,FBI
2,498758,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,2006,March,1,Murder or Manslaughter,...,Unknown,Unknown,0.0,Unknown,Unknown,Unknown,Handgun,0.0,0.0,FBI
3,498759,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,2006,March,2,Murder or Manslaughter,...,Unknown,Male,0.0,Black,Unknown,Daughter,Blunt Object,0.0,1.0,FBI
4,498760,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,2006,March,3,Murder or Manslaughter,...,Unknown,Unknown,0.0,Unknown,Unknown,Unknown,Handgun,0.0,0.0,FBI

Antes de proceder con los análisis debemos eliminar la respuesta 'Unknown' en la variable de sexo.

### **EJ022.**

Para el banco de datos `wine` se desea comparar los valores de diferentes variables: `citric acid`, `pH`, `alcohol` en función de la calidad del vino (`quality`) utilizando la agrupación `bad` (`quality` < 6.5), `good` (`quality` >= 6.5) (Utiliza la función cut para discretizar). Se pide para cada variable:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?


Podemos cargar los datos con:

In [ ]:
# LECTURA
url = 'https://raw.githubusercontent.com/jmsocuellamos/DataPython/main/winequality-red.csv'
winequality = pd.read_csv(url)
winequality

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

### **EJ023.**

Un fabricante tiene la alternativa de utilizar el servicio postal o un trasportista privado para enviar sus pequeños embarques. Para facilitar la elección, el fabricante selecciona 10 destinos y envía parte de sus embarques por cada medio. Los tiempos de entrega (en días) aparecen a continuación. Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?


Podemos cargar los datos con:

In [ ]:
datos ={"Tiempos": [3,4,5,4,8,9,7,10,9,9,2,2,3,5,4,6,9,6,7,6],
      "Envio": ["Postal", "Postal","Postal","Postal","Postal","Postal"
      ,"Postal","Postal","Postal","Postal", "Privado","Privado","Privado",
                "Privado","Privado","Privado","Privado","Privado","Privado",
                "Privado"]}
ifmean023 = pd.DataFrame(datos)
ifmean023.head(5)

   Tiempos   Envio
0        3  Postal
1        4  Postal
2        5  Postal
3        4  Postal
4        8  Postal

### **EJ024.**

Un fabricante de compresores de aire y bombas para neumáticos quiere probar dos modos de exhibir sus mercancías en los puntos de venta. Sus productos se venden a través de tiendas independientes de autopartes, que varían enormemente en sus volúmenes de venta. Un total de 28 tiendas están de acuerdo en participar por un mes en la exposición. Las tiendas se agrupan por pares según su volumen anual de ventas. Se selecciona aleatoriamente una de las dos tiendas más grandes para recibir los exhibidores tipo A, mientras que la otra recibe el modo B. Lo mismo se hace con las tiendas en tercer y cuarto lugar por su tamaño, y así sucesivamente hasta llegar a las más pequeñas. Se registran las ventas durante un periodo de un mes que aparecen a continuación. Se pide:

* ¿Cuál es el parámetro poblacional relevante para este problema?
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?


Podemos cargar los datos con:

In [ ]:
datos ={"Ventas": [46,39,40,37,32,26,21,23,20,17,13,15,11,8,37,42,37,38,27,19,
                   20,17,20,12,12,9,7,2],
      "Tienda": ["A","A","A","A","A","A","A","A","A","A","A","A","A","A","B",
                 "B","B","B","B","B","B","B","B","B","B","B","B","B"]}
ifmean024 = pd.DataFrame(datos)
ifmean024.head(5)

   Ventas Tienda
0      46      A
1      39      A
2      40      A
3      37      A
4      32      A

### **EJ025.**

Un fabricante de insecticidas esta probando diferentes insecticidas (A,B, C, D, E, y F) para agricultura. Cada insecticida se aplica sobre un mismo conjunto de insectos en diferentes campos de cultivo (12 para cada insecticida) y se registra el número de insectos vivos. Se pide:

* Representa gráficamente la información contenida en la base de datos
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?

Podemos cargar los datos con:

In [ ]:
datos ={"Vivos": [10, 7, 20, 14, 14, 12, 10, 23, 17, 20, 14, 13, 11, 17, 21,
      11, 16, 14, 17, 17, 19, 21, 7, 13, 0, 1, 7, 2, 3, 1, 2, 1, 3,
      0, 1, 4, 3, 5, 12, 6, 4, 3, 5, 5, 5, 5, 2, 4, 3, 5, 3, 5, 3,
      6, 1, 1, 3, 2, 6, 4, 11, 9, 15, 22, 15, 16, 13, 10, 26, 26, 24,
      13],
      "insecticida": ["A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A",
                      "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B",
                      "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C",
                      "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D",
                      "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E",
                      "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F"]}
ifmean025 = pd.DataFrame(datos)
ifmean025.head(5)

   Vivos insecticida
0     10           A
1      7           A
2     20           A
3     14           A
4     14           A

### **EJ026.**

Se desea estudiar la fabricación de cuatro tipos de máquinas automáticas (maquina) en el cortado de piezas de embutido para envasado. Para ello se toman datos del número de envases sin defecto (produccion) que produce cada máquina durante periodos de una hora. Se pide:

* Representa gráficamente la información contenida en la base de datos
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?

Podemos cargar los datos con:

In [ ]:
datos ={"Maquina": ["M1","M1","M1","M1","M2","M2","M2","M2",
                    "M3","M3","M3","M3","M4","M4","M4","M4"],
      "Produccion": [103, 115, 101, 105, 109, 106, 116, 124, 104, 98, 117,
                99, 128, 117, 121, 130]}
ifmean026 = pd.DataFrame(datos)
ifmean026.head(5)

  Maquina  Produccion
0      M1         103
1      M1         115
2      M1         101
3      M1         105
4      M2         109

### **EJ027.**

Se desea estudiar la fabricación de cuatro tipos de máquinas automáticas (maquina) en el cortado de piezas de embutido para envasado. Para ello se toman datos del número de envases sin defecto (produccion) que produce cada máquina durante periodos de una hora. Se pide:

* Representa gráficamente la información contenida en la base de datos
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?

Podemos cargar los datos con:

In [ ]:
# Lectura de datos
ifmean027 = pd.read_csv("https://goo.gl/3L4EtK")
ifmean027.head(5)

  Group  phosphate
0   H-O        2.3
1   H-O        4.1
2   H-O        4.2
3   H-O        4.0
4   H-O        4.6

### **EJ028.**

Se lleva a cabo un estudio sobre el contenido promedio de grasa (en porcentaje) en la leche del ganado de cinco razas distintas canadienses. Para ello se consideran veinte ejemplares de pura raza (diez de dos años y diez maduras de más de cuatro años de cada una de cinco razas). Ignorando la varaible que identifica la edad del animal, se pide:

* Representa gráficamente la información contenida en la base de datos
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?

Podemos cargar los datos con:

In [ ]:
# Lectura de datos
ifmean027 = pd.read_csv("https://goo.gl/J2ZKWK")
ifmean027.head(5)

   Butterfat     Bread     Age
0       3.74  Ayrshire  Mature
1       4.01  Ayrshire   2year
2       3.77  Ayrshire  Mature
3       3.78  Ayrshire   2year
4       4.10  Ayrshire  Mature

### **EJ029.**

La convección es una forma de transferencia de calor por los fluidos debido a sus variaciones de densidad por la temperatura; las partes calientes ascienden y las frías descienden formando las corrientes de convección que hacen uniforme la temperatura del fluido. Se ha realizado un experimento para determinar las modificaciones de la densidad de fluido al elevar la temperatura en una determinada zona. Se pide:

* Representa gráficamente la información contenida en la base de datos
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?

Podemos cargar los datos con:

In [ ]:
datos ={"Densidad": [21.8, 21.9, 21.7, 21.6, 21.7, 21.7, 21.4, 21.5, 21.4,
              21.9, 21.8, 21.8, 21.6, 21.5, 21.9, 22.1, 21.85, 21.9],
      "Temperatura": ["T100","T100","T100","T100","T100",
                      "T125","T125","T125","T125",
                      "T150","T150","T150","T150","T150",
                      "T175","T175","T175","T175"]}
ifmean029 = pd.DataFrame(datos)
ifmean029.head(5)

### **EJ030.**

Un laboratorio de reciclaje controla la calidad de los plásticos utilizados en bolsas. Se desea contrastar si existe variabilidad en la calidad de los plásticos que hay en el mercado. Para ello, se eligen al azar cuatro plásticos y se les somete a una prueba para medir el grado de resistencia a la degradación ambiental. De cada plástico elegido se han seleccionado ocho muestras y los resultados de la variable que mide la resistencia son los de la tabla adjunta. Se pide:

* Representa gráficamente la información contenida en la base de datos
* Establece el contraste de hipótesis adecuado para el problema planteado
* Resuelve el contraste con un nivel de significación del 5% y establece a que conclusión puedes llegar con la información recogida?

Podemos cargar los datos con:

In [ ]:
datos ={"Resistencia": [135, 175, 97, 169, 213, 171, 115, 143,
                 275, 170, 154, 133, 219, 187, 220, 185,
                 169, 239, 184, 222, 253, 179, 280, 193,
                 115, 105, 93, 85, 120, 74, 87, 63],
      "Plastico": ["PA","PA","PA","PA","PA","PA","PA","PA",
                   "PB","PB","PB","PB","PB","PB","PB","PB",
                   "PC","PC","PC","PC","PC","PC","PC","PC",
                   "PD","PD","PD","PD","PD","PD","PD","PD"]}
ifmean030 = pd.DataFrame(datos)
ifmean030.head(5)

   Resistencia Plastico
0          135       PA
1          175       PA
2           97       PA
3          169       PA
4          213       PA